//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agenda_Again.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customers()
        {
            this.Appointments = new HashSet<Appointments>();
        }
    
        public int idCustomer { get; set; }
        public string lastname { get; set; }
        public string firstname { get; set; }
        public string mail { get; set; }
        public string phoneNumber { get; set; }
        public int budget { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointments> Appointments { get; set; }

        //Nne pas activer sinon ça fonctionne pas !
        //public static implicit operator Customers(Customers v) 
        //{
        //    throw new NotImplementedException();
        //}
    }
}
